spring.application.name=paymentservice
spring.config.import=optional:configserver:

# 1. Flip this back to true so the new starter handles it!
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 2. Database connection configurations
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# 3. Hibernate flags
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
